Feat/test contest handler
traPtitech/traPortfolio pull request #171
Opened 2021-11-11 15:43 UTC by Hosshii

2021-11-12 09:54 UTC, Ras96 requested changes
気になったところ数点レビューしました:pray:

2021-11-12 09:54 UTC, Ras96 commented on interfaces/handler/contest_test.go
> +						ID:     repoContestTeamDetail.ContestTeam.ID,
```suggestion
						ID:     repoContestTeamDetail.ID,
```

2021-11-12 09:54 UTC, Ras96 commented on interfaces/handler/contest_test.go
> +				return handler.ContestTeamDetailResponse{}, fmt.Sprintf("/api/v1/contests/invalid/teams/%s", random.UUID().String())
個人的にはグローバルに`const invalidID = "invalid"`みたいなやつ置いた方が好きです
微妙だったら変えなくてもおっけーです:ok_hand:

あとほかのとこ付けないなら`.String()`つけなくてもいいかな～と思いました

2021-11-12 09:54 UTC, Ras96 commented on interfaces/handler/contest_test.go
> +				th.Service.MockContestService.EXPECT().CreateContestTeam(gomock.Any(), contestID, gomock.Any()).Return(nil, repository.ErrNotFound)
ここの後ろの`gomock.Any()`特別理由がなければ書いた方がいい気がします:pray:

2021-11-12 09:54 UTC, Ras96 commented on interfaces/handler/contest_test.go
> +				th.Service.MockContestService.EXPECT().CreateContestTeam(gomock.Any(), contestID, gomock.Any()).Return(nil, repository.ErrAlreadyExists)
こっちも

2021-11-13 11:20 UTC, Hosshii commented on interfaces/handler/contest_test.go
> +				return handler.ContestTeamDetailResponse{}, fmt.Sprintf("/api/v1/contests/invalid/teams/%s", random.UUID().String())
const invalidIDを定義して、それをsprintfでやる感じですか？（いまinvalidって直に書いてるのをやめて）

.String()はけします🙏

2021-11-13 11:21 UTC, Ras96 commented on interfaces/handler/contest_test.go
> +				return handler.ContestTeamDetailResponse{}, fmt.Sprintf("/api/v1/contests/invalid/teams/%s", random.UUID().String())
です:thumbsup:

2021-11-13 11:31 UTC, Hosshii commented on interfaces/handler/contest_test.go
> +				th.Service.MockContestService.EXPECT().CreateContestTeam(gomock.Any(), contestID, gomock.Any()).Return(nil, repository.ErrNotFound)
args定義するようにしました

2021-11-13 11:31 UTC, Hosshii commented on interfaces/handler/contest_test.go
> +				th.Service.MockContestService.EXPECT().CreateContestTeam(gomock.Any(), contestID, gomock.Any()).Return(nil, repository.ErrAlreadyExists)
こっちも

2021-11-13 11:47 UTC, Hosshii commented
なおしました

2021-11-13 11:50 UTC, Ras96 approved these changes
LGTM:thumbsup:

2021-11-13 11:51 UTC, merged