go db setting
traPtitech/traPortfolio pull request #3
Opened 2020-08-22 15:14 UTC by Hosshii

dbのsetup

2020-09-04 09:31 UTC, Hosshii commented
tblsはまだ

2020-09-06 17:12 UTC, Hosshii commented
tblsもできるようにした
やり方があんまり綺麗じゃないからtraqみたいにやった方がいいかもしれない
migrationはまだ

2020-09-07 04:24 UTC, Hosshii commented
- db関係の追加
- /userと/pingのエンドポイント追加
- Makefileとdocker関係の追加
- tblsの追加
をしました。お願いします🙏

2020-09-07 13:05 UTC, sapphi-red commented on .dockerignore
> +/vendor/
```suggestion
```
`/vendor/`ってつくられる？

2020-09-07 13:18 UTC, sapphi-red commented
めっちゃよさだと思う
(クリーンアーキテクチャ知らないからずれたこと言うかも)

- `controller`って`echo`の`c.Bind`が担ってると思うから自前実装しなくていいと思う
- `controller`を自前実装しなくていいから、`usecase`って今回はHTTPのリクエストの内容受け取ってレスポンス返す方法しかないからハンドラーと同一のものだと思う
  - あとからCLIみたいなの生える可能性はほぼないだろうし、もしそうならそのときにリファクタすべきだと思う

2020-09-07 15:10 UTC, Hosshii commented
自分で実装したのはechoに依存させたくなかったからだと思う。(自分もまだ完全には理解できてないから間違ってるかもしれない）
もう少し良くできそうな気がするから変えてみる。

2020-09-08 06:11 UTC, sapphi-red commented
フレームワーク差し替える予定があるとかフレームワークが死ぬときも使われるっていう可能性があるなら依存させないほうがいいと思うけど、予定ないし書きなおすだろうし依存させて良いと思う

依存させないのは将来的にメンテしやすいけどそれをくみ上げることはコストだから天秤かけるとよいと思ってる

2020-09-08 14:11 UTC, Hosshii commented
controllerとinteractorを削除してusercase内にhandlerを作った。

2020-09-08 16:06 UTC, sapphi-red reviewed
:yosa: 👍

2020-09-08 16:06 UTC, sapphi-red commented on go.mod
> +	github.com/labstack/echo v3.3.10+incompatible
echo v4にしたい:pray: (importの末尾に`v4`つけたらほぼ動くとおもう)

2020-09-09 03:59 UTC, Hosshii commented
修正した🙏

2020-09-16 14:08 UTC, sapphi-red requested changes
traPortfolioっていうバイナリ含まれてるからそれgitから消して.gitignoreに入れてほしい:pray:

たぶんこれだけ:bowing_man:

2020-09-16 14:08 UTC, sapphi-red commented on infrastructure/router.go
> +	e.GET("/users", api.User.Users)
ここ全部`/api`以下に移してほしい
`/api`でグループつくってそれに生やす感じで

2020-09-16 14:08 UTC, sapphi-red commented on infrastructure/router.go
> +	e.POST("/create", api.User.Add)
このエンドポイント必要ないと思う

2020-09-16 16:59 UTC, Hosshii commented on infrastructure/router.go
> +	e.POST("/create", api.User.Add)
updateとかdeleteの方ではない？

2020-09-17 01:21 UTC, sapphi-red commented on infrastructure/router.go
> +	e.POST("/create", api.User.Add)
あ、deleteもいらなかった

ユーザーが存在するかはtraQ/portalと同期するからportfolioで作成できると必要がないとおもう

2020-09-17 04:49 UTC, Hosshii commented
修正した🙏

2020-09-17 12:20 UTC, sapphi-red approved these changes
:tada:

2020-09-17 12:20 UTC, merged