add project_handler_integration_test
traPtitech/traPortfolio pull request #379
Opened 2022-08-10 05:34 UTC by mehm8128

2022-08-10 05:46 UTC, Ras96 reviewed
ありがとうございます！
draftなんですが気になったとこだけ:eyes:

2022-08-10 05:46 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +			handler.ConvertError(t, repository.ErrNotFound),
`testutils.HTTPError`っていう関数を用意したのでそれを使って具体的にエラーを書いてくれるとありがたいです
他のとこもお願いします

2022-08-10 05:46 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +func TestAddProjecct(t *testing.T) {
```suggestion
func TestCreateProjecct(t *testing.T) {
```

2022-08-10 05:46 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +				Members: []handler.MemberIDWithYearWithSemesterDuration{{duration, userId}, {duration, userId}},
これ成功してるっぽいですが同一IDのメンバーは弾きたさがありますね、、
issueは建てておくのでとりあえずID2つ用意してメンバーに追加しといてもらえると助かります

2022-08-10 05:46 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +
```suggestion
```

2022-08-10 05:46 UTC, Ras96 commented on util/mockdata/handler.go
>  	HMockProject        = CloneHandlerMockProject()
もし`HMockProject`(単数)の方使わなそうだったら消しちゃってOKです:+1:
無かったらそのままで

2022-08-11 03:22 UTC, mehm8128 commented
カオスなことになってるので一旦メモ
get projectmembersのレスポンスにduerationを追加
↓
単体テストにエラーが出る
↓
swagger直す
↓
型が変わったから結合テスト大量に落ちるようになった

2022-08-11 03:23 UTC, Ras96 commented
このコミットから別PRに分けた方がいいかもです

2022-08-11 03:28 UTC, mehm8128 commented
やっぱりそうですよね、分けます
このPRを"change mock user uuid"までにして、"add duration in response"のコミットは別のPRにした方がいいですか？

2022-08-11 04:28 UTC, Ras96 commented
その方が良さそうです👍

2022-08-22 05:01 UTC, Ras96 requested changes
動作はいいと思います:thumbsup:
細かいところいくつか:pray:

2022-08-23 01:59 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +		"400 invalid name": {
invalidよりemptyの方が具体的でよさそう

2022-08-23 12:25 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +			uuid.Nil,
ここのprojectIDは`random.UUID()`だと思います(エラーが`nil id`になってる)
この下のケースも同様です

2022-08-23 12:25 UTC, Ras96 commented on integration_tests/handler/project_test.go
> +		},
ここもケース名はemptyの方がよさそうです

また、
```
handler.DeleteProjectMembersJSONRequestBody{},
```
と
```
handler.DeleteProjectMembersJSONRequestBody{
  Members: []uuid.UUID,
}
```
はどちらも400を出すはずなので一応これのケースも追加しておいてほしいです(ケース名はあんまりいい感じの思いつかないけど`empty memberIDs`とか適当に埋めてもらえると:pray:)

2022-08-24 02:59 UTC, merged