一覧系APIでlimitを指定できるようにする
traPtitech/traPortfolio pull request #398
Opened 2022-08-28 09:21 UTC by 20jun01

現状報告のためDraftのPRを作成しました。
GetUsersのlimitの実装を試みています。

2022-10-04 12:06 UTC, Ras96 reviewed
少しだけ:pray:

2022-10-04 12:06 UTC, Ras96 commented on docs/swagger/traPortfolio.v1.yaml
> +        default: 1e9
デフォルトは0にして非負のときlimitが作用するみたいな感じにした方がいいかもです:eyes:

2022-10-04 12:06 UTC, Ras96 commented on docs/swagger/traPortfolio.v1.yaml
> +        - $ref: '#/components/parameters/limit'
上に合わせて`limitInQuery`にしといてほしいです:pray:

2022-10-04 12:29 UTC, Ras96 reviewed
コメントしました:pray:

2022-10-04 12:29 UTC, Ras96 commented on interfaces/repository/user_impl.go
> +		}
全件取得してから絞ると余分なデータまで取ることになるのでgormのLimitをラップしたものをSQLHandlerに実装するのが良いと思います
[limit](https://gorm.io/ja_JP/docs/query.html#Limit-amp-Offset)

2022-10-04 13:08 UTC, Ras96 reviewed
少しだけ

2022-10-04 13:08 UTC, Ras96 commented on infrastructure/sqlhandler.go
> +
ここ空行2行あってlinterに怒られてるので`make lint`してもらえると:pray:

2022-10-04 13:08 UTC, Ras96 commented on interfaces/repository/user_impl.go
> +		Limit(limit).
これだとlimitが指定されてないときにゼロ値の0が採用されてしまうはずなので
```go
tx := repo.h.Where().Find()

if limit > 0 {
tx = tx.Limit(limit)
}
```

みたいに書くとよいと思います

2022-10-05 23:13 UTC, 20jun01 commented on interfaces/repository/user_impl.go
> +		Limit(limit).
これについて、implement limitのcommitの時に、gormのLimitが-1だとlimit無しで0以上はその数取得の仕様上defaultが-1の方がいいかと思いyamlのdefaultを変更したのですが、0の方が都合よかったら戻してこの実装にします。

2022-10-05 23:16 UTC, 20jun01 commented on infrastructure/sqlhandler.go
> +
ここは直前のcommit(add limit~)でサイレントで修正しててわかりにくくて申し訳ないです。

2022-10-09 04:43 UTC, Ras96 reviewed
コメントしました:pray:
あと今更なんですがCodecovからwarning出てるので新規機能のテストも書いてほしいです:bow:

2022-10-09 04:43 UTC, Ras96 commented on interfaces/repository/user_impl.go
> +		Limit(limit).
これか
https://gorm.io/ja_JP/docs/query.html#Limit-amp-Offset

-1だとLimitキャンセルできるの知らなかったんですが-1でいいと思います:+1:

ただswaggerのデフォルトが-1なのは意味が変わってくると思うので(本来のデフォルトは制限なしなので)、defaultの行消しちゃっていいと思います
若干↓とは勝手が違いそう
https://swagger.io/docs/specification/describing-parameters/#default

2022-11-09 02:34 UTC, Ras96 commented on interfaces/repository/user_impl_test.go
> +			name: "Success_With_Limit1",
successのテストケースは上の方に追加してもらえると助かります:pray:

2022-11-22 12:31 UTC, Ras96 requested changes
ちょっとだけ

2022-11-22 12:31 UTC, Ras96 commented on interfaces/repository/user_impl_test.go
> +				},
domain.NewUserが使えそうです

2022-11-22 12:31 UTC, Ras96 commented on interfaces/repository/user_impl_test.go
> +				f.h.Mock.ExpectQuery(makeSQLQueryRegexp(fmt.Sprintf("SELECT * FROM `users` WHERE `users`.`id` IN (?,?,?) LIMIT %v", args.args.Limit.Int64))).WithArgs(want[0].ID, want[1].ID, want[2].ID).WillRetur
%v->%dかな

2022-11-22 23:59 UTC, Ras96 commented
actionsのログを見るとpanicしてるのでそれだけ直してもらえると🙏

2023-01-17 12:27 UTC, ras0q commented
https://github.com/traPtitech/traPortfolio/pull/448 で同じようなテスト失敗があったのでmainマージしたら直ったりしないですかね

2023-01-17 12:42 UTC, ras0q commented
https://github.com/traPtitech/traPortfolio/pull/448#discussion_r1048337550

2023-01-23 05:00 UTC, ras0q approved these changes
遅れました LGTM:thumbsup:

2023-01-25 11:04 UTC, merged