update時の存在確認にfor updateを取る
traPtitech/traPortfolio pull request #412
Opened 2022-09-20 03:39 UTC by mehm8128

close https://github.com/traPtitech/traPortfolio/issues/370

2022-09-20 04:20 UTC, Ras96 requested changes
いくつか:pray:

2022-09-20 04:20 UTC, Ras96 commented on interfaces/repository/project_impl_test.go
> +					repo := NewProjectRepository(f.h, f.portal)
- 同一の`ProjectRepository`に対して並行にUpdate処理を走らせたときにpanicしないことを確かめたいので、`ctrl`～`repo`はforループの外に出した方がよさそうです

- 一応単一で走らせた時の確認もあった方がいいと思うので消した箇所(変更前の519行目)も残しておいてもらえると助かります:pray:

- `wg.Wait()`をしないと`tt.assertion`が終わる前に `t.Run`の処理が終わってしまうので最後につけ足してほしいです
  - Ref: [traQ#1488](https://github.com/traPtitech/traQ/pull/1488/files#diff-c254218ce57712ae014e838a7d672dcf299abc8ab3e8a9251d4c3c7324740161)

2022-09-20 04:20 UTC, Ras96 commented on interfaces/database/sqlhandler.go
> +	Clauses(conds ...clause.Expression) SQLHandler
gorm等に依存すると結合が密になってしまうため、`FirstForUpdate`みたいな抽象的なメソッドを定義してその具体的な実装をgorm/clauseを使ってinfrastructure/sqlhandler.goで書くのがいいと思います:eyes:

2022-09-20 04:35 UTC, Ras96 commented on interfaces/repository/project_impl_test.go
> +					repo := NewProjectRepository(f.h, f.portal)
1個目ループの外に出すとsetupに3回分処理書かないといけなくなりそうだから嘘かも
setupとUpdate処理だけループの中に入れたら何とかなったりしないかな

2022-09-20 08:22 UTC, Ras96 commented
sqlmockは登録した順に呼ばれないとエラーになるので、並行処理のモックをsqlmockで書くのは厳しいかも
単体テストは今のmainのままにして、結合テストで並行処理が正しく動くか確かめるので十分だと思います

2022-09-20 12:32 UTC, mehm8128 commented
結合テスト書いてみたのですが、mutex使ってるところがなんか微妙な気がしてるのですがどうですか

2022-09-20 12:42 UTC, Ras96 commented
```go
err := repo.UpdateProject(project1.ID, &arg1)
```
にはロックがかかってないので良いと思います！

ただわざわざ構造体を作らなくてもテストの中でmutexを変数として定義すれば十分だとは思います

2022-10-04 12:03 UTC, Ras96 commented
再現できないので一旦放置

2024-01-11 12:03 UTC, ras0q commented
かなり古くなってしまったので一旦closeします
問題が起きたら直しましょう

2024-01-11 12:03 UTC, closed without merging