domain の iota を全部 uint8に
traPtitech/traPortfolio pull request #439
Opened 2022-10-18 13:15 UTC by grkon03

これで合ってますかね？:eyes:

2022-10-20 23:32 UTC, Ras96 commented on domain/user.go
> +	HOMEPAGE uint8 = iota
他のiota同様AccountTypeみたいな型を定義するのがよさそうです

2022-10-20 23:36 UTC, Ras96 commented on domain/event.go
> +	EventLevelAnonymous EventLevel = iota // 匿名で公開
横に長くなってしまうので
`// EventLevelAnonymous 匿名で公開`
みたいなのを各定数の上に書くとよさそうです👍

2022-10-20 23:37 UTC, Ras96 commented on domain/user.go
> +	Type        uint8
ここもAccountTypeの方が好ましいですね

2022-10-20 23:39 UTC, Ras96 commented on interfaces/handler/user.go
> +func newAccount(id uuid.UUID, displayName string, atype uint8, url string, prPermitted bool) Account {
ここも

2022-10-20 23:40 UTC, Ras96 commented on usecases/repository/user_repository.go
> +	Type        uint8
ここも

2022-11-22 13:09 UTC, grkon03 commented
`model.Account` の Type の型も `domain.AccoutType` に変えた方がよいですか？

2022-11-22 13:39 UTC, Ras96 requested changes
いくつか:pray:

2022-11-22 13:39 UTC, Ras96 commented on integration_tests/repository/user_test.go
> +		account1.Type = domain.AccountType(args.Type.Int64)
optional.Uint8型にするのがよさそう

2022-11-22 13:39 UTC, Ras96 commented on interfaces/handler/user_test.go
> +					Type:        domain.AccountType(uint8(reqBody.Type)),
型変換いらなそうです

2022-11-22 13:39 UTC, Ras96 commented on interfaces/handler/user_test.go
> +					Type:        domain.AccountType(uint8(reqBody.Type)),
ここも

2022-11-22 13:39 UTC, Ras96 commented on docs/swagger/traPortfolio.v1.yaml
> +      x-go-type: uint64
```suggestion
      x-go-type: uint8
```

2022-11-22 13:57 UTC, Ras96 commented on domain/user.go
> +type AccountType uint8
これはiotaの直前に書く方がいいです

2023-01-24 00:45 UTC, merged