teamCountを除去&実装の修正
traPtitech/traPortfolio pull request #443
Opened 2022-11-04 06:40 UTC by mehm8128

2022-11-06 09:09 UTC, Ras96 requested changes
いくつか:pray:

2022-11-06 09:09 UTC, Ras96 commented on domain/user.go
> +	Name      string    // チーム名
ここコメントがコンテストIDとコンテスト名ですね

2022-11-06 09:09 UTC, Ras96 commented on interfaces/handler/oapi_types_gen.go
> +	Team ContestTeam `json:"team"`
今更で申し訳ないんですが1人が複数チームに所属する可能性がありそうなので配列の方がよさそうですね

2022-11-06 09:09 UTC, Ras96 commented on interfaces/handler/user_test.go
> +				},
ここはnewUserContestを使ってもらえると:pray:

2022-11-06 09:09 UTC, Ras96 commented on interfaces/repository/user_impl.go
> +			},
ユーザーがnチームに属していたらn個同じコンテストが返る状態になっているので配列に直したうえででここもコンテストの重複がないように修正してほしいです:pray:

2022-11-06 09:20 UTC, mehm8128 commented on interfaces/handler/oapi_types_gen.go
> +	Team ContestTeam `json:"team"`
1人が複数チームに所属することってあるんですかね🤔
今までにこんな大会でそういうことがあったみたいな例ありますか？

2022-11-06 11:37 UTC, Ras96 commented on interfaces/handler/oapi_types_gen.go
> +	Team ContestTeam `json:"team"`
いい感じの事例が思いつかないんですがTAが重複するとかはあってもおかしくないと思います
今の仕様上はありえちゃうのと、その場合にid(コンテストID)をkeyに使ったときに重複が生じちゃうがあまり良くないと思ってます

2022-11-06 11:43 UTC, mehm8128 commented on interfaces/handler/oapi_types_gen.go
> +	Team ContestTeam `json:"team"`
なるほどです、確かに仕様上あり得ちゃうのであればまずそうですね
直してみます

2022-11-06 14:44 UTC, Ras96 reviewed
ちょっとだけ:pray:

2022-11-06 14:44 UTC, Ras96 commented on interfaces/repository/user_impl.go
> +		}
コンテストを取るクエリが2回に増えちゃうので、もともとあったクエリのみを使って↓みたいにやるのがいいと思います:eyes:(変数名とかはいい感じに:pray:)

```go
contestsMap := make(map[uuid.UUID]*domain.userContest)
for _, v := range contestTeamUserBelongings {
  if c, ok := contestsMap[v.ContestTeam.Contest.ID]; ok {
  //チーム追加
  } else {
  //コンテスト情報埋める
  }
}
```

2022-11-06 15:01 UTC, mehm8128 commented on interfaces/repository/user_impl.go
> +		}
こんなにきれいに書けるんですね🧐

2022-11-06 15:44 UTC, Ras96 reviewed
内容はよさそうです:love_you_gesture:
書きかただけ:pray:

2022-11-06 15:44 UTC, Ras96 commented on interfaces/repository/user_impl.go
> +			contestsMap[v.ContestTeam.ContestID].Teams = append(contestsMap[v.ContestTeam.ContestID].Teams, &domain.ContestTeam{
ここ`*domain.UserContest`が入ってるのでifの第一引数でかけたりしないですかね？
```go
if c, ok := contestsMap[~]; ok {
  c.Teams = append(c.Teams, ~~
```

みたいなことです

それとこのfor文の中では`v.ContestTeam`しか使ってないのでそれも変数で置くと見やすいと思います:eyes:

2022-11-07 04:18 UTC, mehm8128 commented on interfaces/repository/user_impl.go
> +			contestsMap[v.ContestTeam.ContestID].Teams = append(contestsMap[v.ContestTeam.ContestID].Teams, &domain.ContestTeam{
```
if c, ok := contestsMap[~]; ok {
  contestsMap[ct.ContestID].Teams = append(c.Teams, ~~
```
左辺はcを使ってもなぜか元のmapの値が変化してなさそうで、こうならできました🤔

2022-11-08 12:17 UTC, Ras96 commented on domain/user.go
> +	Teams     []*ContestTeam
```suggestion
	Teams     []*ContestTeam // ユーザーが所属するチームのリスト
```
みたいなのがあると良いです

2022-11-08 12:36 UTC, Ras96 commented on interfaces/repository/user_impl.go
>  			})
codecovにカバーされてないって言われてるのでチームが複数のテストケースを書いてもらえると:pray:
(今あるやつのlen=1のTeamsを複数にするとかでいいです)

2022-11-08 14:23 UTC, Ras96 commented on interfaces/repository/user_impl_test.go
> +				}
外側でfor使うならAddRowもforで書くのが自然な気がします

2022-11-08 14:30 UTC, merged