アカウントのURLバリデーションを厳しく
traPtitech/traPortfolio pull request #455
Opened 2022-11-13 07:30 UTC by mehm8128

close https://github.com/traPtitech/traPortfolio/issues/359

テスト落ちてるところありますが一旦方針の確認をしてほしいです
多分テスト落ちてるところは`accountType`が`nil`で渡されてるのに`uint()`してるあたりがまずそうです

2022-11-13 07:51 UTC, Ras96 requested changes
パッと見で気になったとこ書きました:eyes:

2022-11-13 07:51 UTC, Ras96 commented on domain/user.go
> +)
- `TWITTER`と`TWITTERURL`(Goの書き方的に大文字である必要はなさそうだけど)が分離しているのがあまりよくない気がするので、グローバルに`var urlPrefix map[uint]string`みたいなのを持つ方がよさそうです
  - `NumberToAccountURL`もそれから取ってくると良いかも
- ちゃんとやるなら`url.URL`で管理して`Schema`、`Hostname()`、`Path`が一致するかを見るのがいいと思います

2022-11-13 07:51 UTC, Ras96 commented on interfaces/handler/validator.go
> +	}
ここはprefixしか見なくていいなら https://pkg.go.dev/strings#HasPrefix を使うのがよさそうです
domainでprefixをmapで持てば`	if r.Type == 0 || r.Type == 1 {`の場合分けもいらなくなるはず

2022-11-13 07:51 UTC, Ras96 commented on interfaces/handler/validator.go
> +	}
おなじ

2022-11-13 07:51 UTC, Ras96 commented on util/random/random.go
> +}
ここもあまり`accountType`に依存してほしくなくて(するなら`0`じゃなくて`domain.HOMEPAGE`を使ってほしい)、domainのprefixからスキーマ外してもいいかもです

2022-11-13 13:15 UTC, mehm8128 commented on interfaces/handler/validator.go
> +	}
prefix以外に、例えばユーザーIDに`mehm8128/mehm8128-portfolio`って入力されちゃうとプロフィール以外のページを設定できてしまうのでスラッシュが入らないようにしてるので`HasPrefix`は使えなさそうです(クエリパラメータで使われるクエスチョンマークも除いた方がよさそうですね)

2022-11-13 13:49 UTC, Ras96 commented on interfaces/handler/validator.go
> +	}
確かに:bow:
正規表現でやるならアプリごとに規定があるはずなので`/[0-9a-zA-Z\_\-]{1,26}/`みたいにホワイトリスト方式で書くとよさそうです

2022-11-13 13:53 UTC, mehm8128 commented on interfaces/handler/validator.go
> +	}
分かりました、やってみます

2022-11-14 05:41 UTC, mehm8128 commented on interfaces/handler/validator.go
> +	}
と思ったんですけど、明示されてなくて実際に登録しようとしてみないと分からなかったり、他のGoogle、Facebook等のアカウントと連携してアカウント作成できたりと、かなりめんどくさそうなのですがどうしましょう...
全部一括して`[a-zA-Z0-9-_.]+`みたいな感じにしてもいいですかね？

2022-11-14 06:18 UTC, Ras96 commented on interfaces/handler/validator.go
> +	}
出来れば個別でやった方が良いですが一時的にそうしてもいいと思います:+1:
別の方法だとhostがあってるか確認した上で実際にリクエスト飛ばしてユーザーが存在するか確認してもいいかも、、？

2022-12-22 14:53 UTC, mehm8128 commented
panicしないようにするために、`validator.go`で`uint()`する前に`r.Type`がnilかどうかの判定すればよさそうなのですが、それでnilだった場合にどういう処理をすればよいか教えてほしいです
`r.Type`が0(=URLが`https://`から始まっていればなんでもOK)として扱うのがよさそうですかね？

2022-12-22 14:58 UTC, ras0q commented on domain/user.go
> +var URLPrefix = map[uint]AccountURL{
URLRegexpかも

2022-12-22 14:58 UTC, ras0q commented on interfaces/handler/validator.go
> +	regexpText := fmt.Sprintf("^https://%s/%s$", domain.URLPrefix[uint(*r.Type)].URL, domain.URLPrefix[uint(*r.Type)].Regexp)
```suggestion
	regexpText := fmt.Sprintf("^https?://%s/%s$", domain.URLPrefix[uint(*r.Type)].URL, domain.URLPrefix[uint(*r.Type)].Regexp)
```
かも、やや自信ない

2022-12-22 15:00 UTC, ras0q commented
r.Type==nilだったらtypeに変更がないのでそもそもvalidateしなくてよさそう
https://github.com/traPtitech/traPortfolio/pull/455#issuecomment-1362933439

2022-12-22 15:08 UTC, mehm8128 commented
typeではなくてURLをvalidateするものなので、typeを変更せずにURLだけ変えた場合にvalidateする必要がありそうな気がします

2022-12-22 15:09 UTC, mehm8128 commented
なので、typeがnilの場合には現在のtypeを取得しないとvalidateできなさそう？

2022-12-22 16:30 UTC, ras0q commented
何も見てなかった:pray:
現在のtypeを取得しないといけなそうなんですがそれも厳しいですね困った、、
とりあえずここでは最初がhttp(s)://で始まるかどうかだけをチェックしてDBに入れる前にチェックするのがいいかな
自信ないので考えます

2022-12-27 13:40 UTC, ras0q requested changes

2022-12-27 13:40 UTC, ras0q commented on domain/user.go
> +}
domainではvalidatorに依存したくないのでここではvd.MatchRuleを返すんじゃなくて`func IsValidURL() bool`みたいなメソッドを立ててその場でtypeとurlみてvalidかどうかチェックするのがいいですね

2022-12-29 10:38 UTC, ras0q commented on domain/user.go
> +}
~~domainの外に出さないので小文字始まりでよさそうです(フィールドも)~~

~~あと構造体名も`accountURLRule`とかの方がいいかな~~

と思ったんですがIsValidで検証するたびにregexp.MustCompileするのもパフォーマンス微妙なのでそもそもmap[AccountType]*regexp.Regexpで持っておくのが良さそうな気がしました

2022-12-29 10:46 UTC, ras0q commented on util/random/random.go
> +}
これはRandAccountURLStringでしか使わないと思うので関数内に入れちゃっていいですね

2022-12-29 10:54 UTC, ras0q commented on interfaces/repository/user_impl.go
> +	}
これ若干記述が分かりにくいのとトランザクションの外でDB処理を行ってるのが気になるので今の366行目のあとでバリデーションするといいと思います
あと今更気づいたんですがTypeだけ変わった時は(HOMEPAGE↔BLOGのとき以外は)絶対バリデーション落ちるのでType変えるときはURLも必須で返させてもいいと思います(これは別PRでいいかな)

2022-12-29 10:58 UTC, ras0q commented on domain/user.go
> +}
AccountTypeのメソッドになってるのが個人的にあんまり好きじゃないです
どちらかというとURLがvalidかどうかを見たいので

↓みたいにふつうの関数にすると若干長いけど意味が分かりやすいと思います
```
domain.AccountType(account.Type).IsValid(args.URL.String)
↓
domain.IsValidAccountURL(domain.AccountType(account.Type), args.URL.String)
```

2022-12-29 14:03 UTC, ras0q requested changes
いくつか:pray:

2022-12-29 14:03 UTC, ras0q commented on util/random/random.go
> +	var AccountURLs = map[uint][]string{
メモ(ここでは直さなくていいです): 複数パターンのrs6lettersみたいなのがあると愚直にアカウント名列挙しなくてよくなりそう

2022-12-29 14:03 UTC, ras0q commented on interfaces/repository/user_impl.go
> +				Error()
これはもう取得してるのでいらないはずですね

2022-12-29 14:03 UTC, ras0q commented on interfaces/repository/user_impl.go
> +			}
ここも

2022-12-29 14:05 UTC, ras0q commented
テストケース足りてないのはtypeとurlのvalidがT&T,T&F,F&Tの3パターンを用意して検証すると怒られがなくなりそうです

2022-12-29 14:09 UTC, mehm8128 commented on interfaces/repository/user_impl.go
> +				Error()
>これ若干記述が分かりにくいのと

ってそういう意味で解決されてたんですねなるほど

2022-12-29 14:59 UTC, ras0q requested changes
ちょっとだけ

2022-12-29 14:59 UTC, ras0q commented on domain/user.go
> +var urlRegexp = map[uint]*regexp.Regexp{
これもIsValidAccountURLの中に入れてもいいかも

2022-12-29 14:59 UTC, ras0q commented on integration_tests/handler/user_test.go
> +				Type: (*handler.AccountType)(&invalidAccountType),
キャストするなら最初からhandler.AccountTypeで宣言するのがよさそう

2022-12-29 15:04 UTC, ras0q requested changes

2022-12-29 15:04 UTC, ras0q commented on domain/user.go
> +type AccountURL struct {
これもう使ってなさそう

2022-12-29 15:04 UTC, ras0q commented on integration_tests/handler/user_test.go
> +					Url:         random.AccountURLString(accountType),
ここもかな
diff見るとまだ直すとこいくつかあったのでおねがい:pray:

2022-12-29 15:17 UTC, ras0q approved these changes
これだけやったらマージしちゃってオッケーです:ok_hand:

2022-12-29 15:17 UTC, ras0q commented on domain/user.go
> +		CTFTIME:    regexp.MustCompile("^https?://ctftime.org/user/[0-9]+$"),
twitterから下はhttps強制しちゃっていいかな

2022-12-29 15:22 UTC, merged