EditContestのintegration test さらに5つ書いた
traPtitech/traPortfolio pull request #457
Opened 2022-11-22 17:38 UTC by 0214sh7

2022-11-22 23:11 UTC, Ras96 requested changes
見ました👀

2022-11-22 23:11 UTC, Ras96 commented on integration_tests/handler/contest_test.go
> +		tooLongString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx
strings.Repeat("a", 260)とかのがわかりやすいかもです

2022-11-22 23:11 UTC, Ras96 commented on integration_tests/handler/contest_test.go
> +			},
テスト名見ればわかるんですが、どこがinvalidなのかわかりやすくしたいのでinvalidなやつ以外は指定しなくてもいいと思います(他も同様、invalid idもbodyの中身空でよさそう)

2022-11-25 08:16 UTC, 0214sh7 commented on integration_tests/handler/contest_test.go
> +		tooLongString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx
そんな記法が

2022-11-25 10:47 UTC, Ras96 commented
あれCreateのnameって必須じゃなかったでしたっけ
なんでテスト通るんだ

2022-11-25 18:11 UTC, 0214sh7 commented
そのはず
ゼロ文字の文字列という変更を明記しても通る
https://github.com/traPtitech/traPortfolio/blob/e907ca8a4e8428c94781a2431c340d3e0f8b41ca/interfaces/handler/validator.go#L36-L44

2022-11-26 11:29 UTC, Ras96 commented
createContestTestでレスポンスの型がswitchにcaseに当てはまってないとかかも
default追加してみても変わらないですか？

2022-11-28 05:25 UTC, Ras96 commented
@0214sh7 
わかった
必須フィールドが空なのと名前が260文字あるのはどっちも同じエラーを吐くので現状のテストとしては成功してる感じですね
エラー出力が弱いのが悪くて、今後エラー文が詳細化されたらfailするはずです
なのでCreateのテストは必須フィールドは埋め直してほしいです:pray:

2022-11-29 12:12 UTC, Ras96 commented on integration_tests/handler/contest_test.go
> -				Name: name,
ここら辺を戻してほしいです

2022-11-29 12:28 UTC, Ras96 approved these changes

2022-11-29 12:28 UTC, merged