TestGetContestTeamのintegration test
traPtitech/traPortfolio pull request #461
Opened 2022-11-29 13:44 UTC by 0214sh7

2022-11-30 10:52 UTC, Ras96 approved these changes
一部修正したらほぼ良さそうです👍

2022-11-30 10:52 UTC, Ras96 commented on integration_tests/handler/contest_test.go
> +	*/
他のPRの内容なので丸ごと消しちゃって大丈夫です

2022-12-01 03:00 UTC, Ras96 requested changes
lint怒られてるのも修正してほしいです:pray:

2022-12-14 06:09 UTC, ras0q requested changes
typoだけ🙏

2022-12-14 06:09 UTC, ras0q commented on util/mockdata/handler.go
> +	HMockContestTeamsDetailsByID = CloneHandlerMockContestTeamsDetailsByID()
TeamDetailsの方が良さそうです

2022-12-22 14:45 UTC, ras0q commented on util/mockdata/handler.go
> +	HMockContestTeamsDetailsByID = CloneHandlerMockContestTeamsDetailsByID()
typoだしなおしときますね

2022-12-22 14:52 UTC, ras0q approved these changes

2022-12-22 14:52 UTC, ras0q commented on util/mockdata/handler.go
> +	HMockContestTeamsDetailsByID = CloneHandlerMockContestTeamsDetailsByID()
使ってないし消しとくか

2022-12-22 14:52 UTC, merged