AddContestTeamのintegration test 1つ書いた
traPtitech/traPortfolio pull request #467
Opened 2022-12-27 13:29 UTC by 0214sh7

2022-12-27 13:43 UTC, ras0q requested changes
ちょっとだけ

2022-12-27 13:43 UTC, ras0q commented on integration_tests/handler/contest_test.go
> +				Id:     uuid.Nil,
後でOptSyncIDで同期的な文言を書いといてもらえると:pray:

2022-12-27 13:43 UTC, ras0q commented on integration_tests/handler/contest_test.go
> +				testutils.AssertResponse(t, tt.statusCode, tt.want, res, testutils.OptSyncID, testutils.OptRetrieveID(&want.Id))
多分TestCreateContestの方もいらないんですが、idをretrieveしても後で使わないのでOptRetrieveID不要ですね

2023-01-10 12:21 UTC, 0214sh7 commented on integration_tests/handler/contest_test.go
> +				Id:     uuid.Nil,
ところでこれ指定しない(行ごと消す)とだとどっちがいいんですか

2023-01-17 00:03 UTC, ras0q commented on integration_tests/handler/contest_test.go
> +				Id:     uuid.Nil,
自分も忘れかけてたのですがそれ用に↓を作ってあります
https://github.com/traPtitech/traPortfolio/blob/8f6d1f1cfff446b87571861aee9a19770968cf5e/integration_tests/testutils/router.go#L61

2023-01-17 00:05 UTC, ras0q approved these changes
ココだけ直してもらえればマージしちゃってOKです:+1:

2023-01-17 00:05 UTC, ras0q commented on integration_tests/handler/contest_test.go
> +				Id:     uuid.Nil, //テスト時にOptSyncIDで同期するため適当
```suggestion
				Id:     testutils.DummyUUID(), //テスト時にOptSyncIDで同期するため適当
```

2023-01-17 12:24 UTC, merged