同じタイプのアカウントを同一ユーザーに追加できなくした
traPtitech/traPortfolio pull request #472
Opened 2023-01-17 13:21 UTC by Tennessine699

resolve: #469

2023-01-25 07:39 UTC, ras0q requested changes
コメントしました
結合テストの方も修正お願いします:pray:

2023-01-25 07:39 UTC, ras0q commented on interfaces/repository/user_impl.go
> +	}
`exist`ここ以外で使わないのであれば変数定義せずに`First(&model.Account{})`とするのが良さそうです

2023-01-25 07:39 UTC, ras0q commented on interfaces/repository/user_impl.go
> +		}
あまり特定のエラーかどうかで分岐してから`err != nil`をする書き方は見ない気がします

↓もあってるかわからないけど自分が書くならこんな感じかも
```go
if err == nil {
  return nil, repository.ErrAlreadyExists
} else {
  if !errors.Is(err, database.ErrNoRows) {
    return nil, convertError(err)
  }
}
```

2023-02-15 06:18 UTC, ras0q reviewed
一点だけ🙏

2023-02-15 06:18 UTC, ras0q commented on integration_tests/repository/user_test.go
> +	accountType2 := domain.AccountType(rand.Intn(int(domain.AccountLimit)/2) + int(domain.AccountLimit)/2)
accountType1をrand(Limit)で作って、accountType2=(accountType1+1+rand(Limit-1))%Limitにするとランダム性が担保されそうな気がします

2023-03-01 22:54 UTC, ras0q commented
あれ409出てるってことは一意性ないのか

2023-03-07 14:11 UTC, ras0q requested changes
少しだけ書きました:pray:

2023-03-07 14:11 UTC, ras0q commented on integration_tests/handler/user_test.go
> +			mockdata.UserID2(),
今はランダムでtypeを決めてますがTwitterじゃないやつを直指定しちゃってOKです
そうすれば他の箇所も含めてUserID2に変える必要はないはず、、？

2023-03-07 14:11 UTC, ras0q commented on integration_tests/handler/user_test.go
> +			mockdata.UserID2(),
ここもtype直指定してUserIDはUserID1にするのがよいと思います
加えてtypeが衝突するテストケースもあるとよさそうです

2023-03-31 16:53 UTC, ras0q requested changes
とりあえず気になったところを書きました
mainにoptional周りでかなり大きい破壊的変更が入っているのでマージしつついい感じに直してもらえると助かります:pray:(やりかた分からなかったら相談乗ります)

2023-03-31 16:53 UTC, ras0q commented on integration_tests/handler/user_test.go
> +				if tt.accountID == mockdata.AccountID1() {
あんまりIDに依存するテストは書きたくないですね
特定の場合のみinsertしたいなら↓みたいに書くとよさそうです
https://github.com/traPtitech/traPortfolio/blob/06d15bd86768a74ef6b3ef4690e43948cfeeb7a4/integration_tests/handler/user_test.go#L602

2023-03-31 16:53 UTC, ras0q commented on integration_tests/repository/user_test.go
> +		accountType3Int64 = int64(6)
`accountType3`も`domain.AccountType`で持つのがよさそうです(最新のmainはoptional.Int64を使わないので)

2023-04-11 13:24 UTC, Tennessine699 commented on integration_tests/repository/user_test.go
> +		accountType2 = domain.AccountType(4)
テストする側からはその値が何に割り当てられているかを知る必要がないからと思っていましたが変えました

2023-04-13 00:53 UTC, ras0q requested changes
いくつか！

2023-04-13 00:53 UTC, ras0q commented on integration_tests/handler/user_test.go
> +			mockdata.UserID2(),
気分の問題だけどuser2を指定してるのにリクエストボディはuser1を引数に作ったtypeとlinkを使ってるのが若干の違和感かも
`accountType2`みたいなのをもう1つ作るといいと思います

2023-04-13 00:53 UTC, ras0q commented on integration_tests/handler/user_test.go
> +			true,
ここtrueにしたのって意図ありますか？(falseでもdbにアクセスする前に400は出そう)

2023-04-13 00:53 UTC, ras0q commented on integration_tests/handler/user_test.go
> +					}
ここはmockdataからじゃなくてGETリクエストを飛ばして対象アカウントを取得してほしいです

2023-04-13 00:53 UTC, ras0q commented on integration_tests/handler/user_test.go
> +				})
これはneedInsertionをtrueにして処理まとめたらいらなそう？

2023-04-13 00:53 UTC, ras0q commented on integration_tests/repository/user_test.go
> +	)
account定義の直前で定義するのが分かりやすそう

2023-04-13 00:53 UTC, ras0q commented on integration_tests/repository/user_test.go
> +	)
他にも何か所かあります

2023-04-13 00:53 UTC, ras0q commented on interfaces/repository/user_impl.go
> +		Where("`accounts`.`type` = ? AND `accounts`.`user_id` = ?", uint8(args.Type), userID).
根拠ないんですが順番逆の方が将来的に早くなったりしませんかね？

2023-04-13 00:53 UTC, ras0q commented on util/mockdata/handler.go
> +
```suggestion
```

2023-04-13 00:53 UTC, ras0q commented on util/mockdata/handler.go
> +	// for ;slices.Contains(holdAccounts, handler.AccountType(checkAccount)); checkAccount++ {}
```suggestion
```

2023-04-13 00:53 UTC, ras0q commented on util/mockdata/handler.go
> +	}
```go
holdAccountsMap := make(map[handler.AccountType]struct{})
// holdAccountsからmapを作る処理...

for i := holdAccountsMap(0); i < handler.AccountType(domain.AccountTypeLimit); i++ {
  if _, ok := holdAccountsMap[i]; !ok {
    return i
  }
}
```
みたいに書けそうです

2023-04-27 01:09 UTC, ras0q requested changes
みました:eyes:

2023-04-27 01:09 UTC, ras0q commented on util/mockdata/handler.go
> +	}
ここら辺の処理、`CloneHandlerMockUserAccountsByID`からユーザーが持っているアカウントの一覧が取れるのでそっちの方がいい気がします

2023-04-27 01:09 UTC, ras0q commented on util/mockdata/handler.go
> +	}
`AccountTypeMockUserDoesntHave`も`CloneHandlerMockUserAccountsByID`から取って0..<domain.AccountLimitで持っていないやつを列挙するのがいいかも

2023-04-27 01:09 UTC, ras0q commented on integration_tests/testutils/assert.go
> +func OptRetrieveAccount(acPtr *handler.Account) Option {
これってPOSTの他のテストでやってるようにテスト内で`json.Unmarshal`使うのだとダメですかね？
Opt~~はassertResponseのオプションとして使う運用にしたいです

2023-05-09 23:01 UTC, ras0q commented
gormのアップデートでおちてる？

2023-05-16 12:50 UTC, ras0q approved these changes

2023-05-16 12:53 UTC, merged