コンテストにチームを追加する前に該当コンテストが存在するかを確認する
traPtitech/traPortfolio pull request #473
Opened 2023-01-17 13:22 UTC by 0214sh7

2023-01-17 13:29 UTC, ras0q requested changes

2023-01-17 13:29 UTC, ras0q commented on interfaces/handler/contest.go
> +	}
ここでコンテストの確認をするんじゃなくて`h.srv.CreateContestTeam(ctx, contestID, &args)`の中で確認してほしいです

2023-01-17 14:12 UTC, 0214sh7 commented
わからない

　　　　　　　　　　　　　　終
　　　　　　　　　　　　制作・著作
　　　　　　　　　　　　━━━━━
　　　　　　　　　　　　　ⓃⒽⓀ

2023-01-24 13:16 UTC, ras0q commented
transaction使わずに実装してるとこも結構あるんですが↓みたいにtransactionの中で存在確認と新規追加ができるといい感じです
https://github.com/traPtitech/traPortfolio/blob/51eaeb5f7c5b4a0b4091308d178af573b6b175ac/interfaces/repository/contest_impl.go#L143-L166

2023-02-07 14:13 UTC, 0214sh7 commented
一箇所直すと芋づる式にほかが落ちる　多分nil uuidのコンテストチームが単体テストにあるのが理由

2023-02-09 09:37 UTC, ras0q requested changes
レビューしました
多分いま落ちいてるのはcontest_implにだけ処理追加してcontest_impl_testにモックの追加してないからですね

2023-02-09 09:37 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +
ここの改行もいらないかな
```suggestion
```

2023-02-14 13:50 UTC, 0214sh7 commented
モックの追加がわかりませんでした

2023-02-14 15:09 UTC, ras0q commented
存在確認のためにやってることはGetContestと同じなのでGetContestのテストのsetupを見ると分かるかもしれない、、、？

2023-02-14 17:11 UTC, ras0q approved these changes
これだけ直したらマージしておっけーです

2023-02-14 17:11 UTC, ras0q commented on interfaces/repository/contest_impl_test.go
> +
```suggestion
```
この空行はなくて良さそうです

2023-02-14 17:14 UTC, ras0q requested changes
嘘でした、単体テストの他のケースにも存在確認のモック追加して欲しいです🙏(これでcoverage落ちてる)

2023-02-15 08:58 UTC, ras0q approved these changes
これ治したらマージしておっけーです

2023-02-15 08:58 UTC, ras0q commented on interfaces/repository/contest_impl_test.go
>  			name: "UnexpectedError",
メソッド内で複数のことをするようになったのでCreateContestFailedとかの方がいいかもです

2023-02-15 09:11 UTC, 0214sh7 commented
え、なんでcoverage落ちるの

2023-02-15 09:14 UTC, ras0q commented
どっかの更新系メソッドで1/2^nの確率でoptionalが全部falseになるとsqlhandler.Updateが行われなくてcoverageが落ちることがありますね
もう1回回すと多分治ります

2023-02-15 09:17 UTC, ras0q commented
https://github.com/traPtitech/traPortfolio/issues/395

2023-02-15 09:49 UTC, ras0q commented
1/2^2n引いた？乱数固定されてるかも
マージしてOKです

2023-02-15 10:18 UTC, 0214sh7 commented
う笑

2023-02-15 10:19 UTC, merged