TeamDetail.MembersをTeamに移した
traPtitech/traPortfolio pull request #484
Opened 2023-03-07 13:46 UTC by 0214sh7

#470

2023-03-07 13:55 UTC, ras0q requested changes
一部レビューしました
テストがコンパイルに失敗してそうです

2023-03-07 13:55 UTC, ras0q commented on interfaces/handler/contest.go
>  	}
ここら辺書いたの多分自分なんですが、Createのときはlen(teams)==0なのでここら辺の処理いらないですね
適当に空配列渡してあげればいいです

2023-03-07 13:55 UTC, ras0q commented on interfaces/handler/contest.go
> +	}
ここもチーム作成時点ではメンバー空なので空スライス渡せばいいです

2023-03-07 14:31 UTC, 0214sh7 commented on interfaces/handler/contest.go
>  	}
たかしに

2023-03-08 03:06 UTC, ras0q commented on interfaces/handler/user_test.go
> +			members := make([]User, len(rcontest.Teams[0].Members))
`rcontest.Teams[0].Members`って現段階だと空になりませんか？

2023-04-11 12:47 UTC, ras0q commented on util/mockdata/handler.go
> +			Members: make([]handler.User, 0),
ここも？

2023-04-18 12:33 UTC, ras0q commented
失敗してるテスト見るとわかるんですが、membersがnilになってるとこは空配列にして欲しいです🙏

2023-07-20 12:55 UTC, ras0q commented
@0214sh7 ここMembers追加し忘れてます
https://github.com/traPtitech/traPortfolio/blob/2c359ca993e06791ec43676c17847608c2c08e60/interfaces/repository/user_impl.go#L541-L551

2023-07-25 13:04 UTC, ras0q commented on docs/swagger/traPortfolio.v1.yaml
> +          description: チームメンバーのUUID
UUIDは偽かも

2023-07-25 13:06 UTC, ras0q commented on integration_tests/repository/user_test.go
> +	expected1 := []*domain.UserContest{newUserContest(&contest1.Contest, []*domain.ContestTeamWithoutMembers{&team1.ContestTeam.ContestTeamWithoutMembers}), newUserContest(&contest2.Contest, []*domain.C
複数行に区切ってもいいかもです

2023-07-25 13:11 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +			},
Members追加し忘れてる？

2023-07-25 13:13 UTC, ras0q commented on interfaces/repository/contest_impl.go
>  		},
ここもメソッドコメントにはMembers別で返すって書いてあるけど一緒に返した方がいい気がする

2023-07-25 13:13 UTC, ras0q commented on interfaces/repository/contest_impl_test.go
>  			},
ここもMembersを追加するべき

2023-07-25 13:22 UTC, ras0q commented on util/mockdata/handler.go
> +		}
members, ok := の方式の方がよくつかわれますね

2023-07-25 13:23 UTC, ras0q commented on util/mockdata/handler.go
> +		//hTeamMembersByID    = CloneHandlerMockContestTeamMembersByID()
コメントは消してほしいです:pray:

2023-07-25 13:24 UTC, ras0q commented on util/mockdata/handler.go
> +		hUserContests = make(map[uuid.UUID][]handler.UserContest, len(hContests))
ここ不用なコメント消すとdiffなくなるはずです

2023-07-27 13:09 UTC, 0214sh7 commented on interfaces/repository/contest_impl.go
> +			},
ContestTeamWithoutMembersを返すべきかもしれない

2023-07-27 13:17 UTC, ras0q commented on docs/swagger/traPortfolio.v1.yaml
> +          description: チームメンバーのUUID
生やしてほしいです:+1:

2023-07-27 13:19 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +			},
いや、このままでよくて追加でMembersを追加するのがよさそうです
実装むずそうだったらもっとちゃんと見ます

2023-07-27 22:52 UTC, ras0q requested changes

2023-07-27 22:52 UTC, ras0q commented on interfaces/handler/oapi_types_gen.go
> +// ContestTeam defines model for ContestTeam.
ここdescription入ってないのなんでだろう
もう1回generateしてもらってもいいですか

2023-07-27 22:52 UTC, ras0q commented on util/mockdata/handler.go
> +				//Teams:    userContestTeams[u.ID][c.Id],
Teams抜いたの理由あったりしますか

2023-07-27 22:52 UTC, ras0q commented on interfaces/handler/user.go
> +		Teams:    make([]ContestTeam, 0),
ここも

2023-08-17 14:50 UTC, 0214sh7 commented on util/mockdata/handler.go
> +				//Teams:    userContestTeams[u.ID][c.Id],
記憶がないけど何故かビルドが通らないから通すために抜いたとかだと思う　[これ](https://github.com/traPtitech/traPortfolio/pull/484#discussion_r1276898462) を修正したらビルド通るので元に戻しました

2023-08-20 01:04 UTC, ras0q commented on interfaces/handler/oapi_types_gen.go
> +// ContestTeam defines model for ContestTeam.
他のXXXDetailもなかった
allofしてると出ないらしい🙃

2023-08-20 01:20 UTC, ras0q requested changes
いくつか🙏

2023-08-20 01:20 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +			}
realnameがprivateな関係でdomain.NewUserという関数があるのでそれを使うといいです

2023-08-20 01:20 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +			Error()
これteam少ないからN+1許容するみたいな話でしたっけ(何も覚えてない)
sqlhandlerにInを追加してWhereのところを
`In("team_id IN (?)", teamIDs)`みたたいに書き換えるとN+1防げます

2023-08-20 01:20 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +		}
同様

2023-08-20 01:20 UTC, ras0q commented on interfaces/repository/contest_impl_test.go
> +						},
どうよう

2023-08-20 01:20 UTC, ras0q commented on interfaces/repository/contest_impl.go
> -		Members:     nil,
なんでnilになってたのか分からないけど空スライスの方が意図にあってるはずなので治しちゃってOKです

2023-08-20 01:20 UTC, ras0q commented on interfaces/repository/contest_impl_test.go
> -				Members:     nil,
ここも空スライスになるはず

2023-08-20 19:58 UTC, 0214sh7 commented
マージまじでしんどすぎてマージ・マジ・マジーロ

2023-08-20 20:39 UTC, 0214sh7 commented on interfaces/repository/contest_impl.go
> +			Error()
N+1を許容するという話はなかったはず　消せるなら消します

2023-08-20 21:10 UTC, 0214sh7 commented on interfaces/repository/contest_impl.go
> +			Error()
Inを実装するの難しくないですか？WhereInとかならまあ

2023-09-26 16:38 UTC, 0214sh7 commented
makeUserNameMapくんが何者なのかよくわかってません、何を引数とするmapですかこれ
https://github.com/traPtitech/traPortfolio/blob/2ab150204ba18571a38c4936e2a99dfeef9a6553/interfaces/repository/contest_impl.go#L224

https://github.com/traPtitech/traPortfolio/blob/2ab150204ba18571a38c4936e2a99dfeef9a6553/interfaces/repository/contest_impl.go#L585-L597

2023-09-29 14:54 UTC, ras0q commented
> makeUserNameMapくんが何者なのかよくわかってません、何を引数とするmapですかこれ
> 
> https://github.com/traPtitech/traPortfolio/blob/2ab150204ba18571a38c4936e2a99dfeef9a6553/interfaces/repository/contest_impl.go#L224
> 
> https://github.com/traPtitech/traPortfolio/blob/2ab150204ba18571a38c4936e2a99dfeef9a6553/interfaces/repository/contest_impl.go#L585-L597

traQ ID = user.Nameですね

2023-09-29 14:54 UTC, ras0q requested changes

2023-09-29 14:54 UTC, ras0q commented on go.mod
> +	github.com/jinzhu/gorm v1.9.16 // indirect
github.com/jinzhu/gorm (Gorm v1)は使ってないはずなのでもう1回go mod tidyして消してもらえますか:pray:

2023-10-05 12:40 UTC, ras0q requested changes

2023-10-05 12:40 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +	}
ここのクエリがテストのsqlmockに反映されてないですね

2023-10-05 13:26 UTC, ras0q commented on interfaces/repository/contest_impl.go
> +	}
`?`→`(?)`

2023-10-26 13:54 UTC, ras0q requested changes

2023-10-26 13:54 UTC, ras0q commented on interfaces/handler/contest_test.go
> +				Members: make([]*domain.User, 0),
ここメンバー1つでもいいので入れ他方がよさそう

2023-10-26 13:54 UTC, ras0q commented on interfaces/handler/contest_test.go
> +				Members: make([]*domain.User, 0),
ここも

2023-10-26 13:54 UTC, ras0q commented on interfaces/handler/contest.go
>  	res := newContestDetail(newContest(contest.ID, contest.Name, contest.TimeStart, contest.TimeEnd), contest.Link, contest.Description, contestTeams)
作成時はチームがないのでここら辺の記述はいらないかも

2023-10-26 13:54 UTC, ras0q commented on interfaces/handler/contest_test.go
> +						Members: make([]*domain.User, 0),
ここらへんも

2023-10-26 22:19 UTC, ras0q approved these changes
いいと思います！感謝

2023-10-26 22:19 UTC, merged