GetUserParamsにlimitno
traPtitech/traPortfolio pull request #501
Opened 2023-03-28 10:06 UTC by 20jun01

- close #500

2023-03-28 15:05 UTC, ras0q commented
直して欲しいのはこれじゃなくて、この前urturnくんが実装してくれたlimitをvalidateしてないってやつですね

2023-03-28 15:06 UTC, ras0q commented
何でこれが必要だと思ったか忘れたんですけど思い出したらかきます

2023-04-07 18:33 UTC, 20jun01 commented
修正箇所あってるか聞きたくていったんisDigitとMinのvalidationつけたんですが、validation何が必要そうですか？

2023-04-09 03:39 UTC, ras0q requested changes
レビューしました
openapiと合わせるならminだけあれば良さそうです:eyes:

2023-04-09 03:39 UTC, ras0q commented on interfaces/handler/validator.go
> +		vd.Field(&p.Limit, vd.Min(1), is.Digit),
```
	// Digit validates if a string contains digits only (0-9)
	Digit = validation.NewStringRuleWithError(isDigit, ErrDigit)
```
らしい
limtiはstringじゃないので`is.Digit`はいらなそうです

2023-04-10 13:32 UTC, ras0q reviewed
良さそうです！
coverageは変わらないんですがLimitがinvalidなテストケースを書いてほしいです(多分忘れてたのこれ)

2023-05-09 23:02 UTC, ras0q commented
単体テストはsetupにモック処理を書く必要がありそうです
結合テストもお願いします🙏

2023-05-10 05:26 UTC, 20jun01 commented
モック処理は、バリデーションで弾かれて到達しないからいらないと思ってたんですが、もしかしてバリデーションは動作しませんか？
`testutil_test.go`の`doRequest`内の`Setup`で`newValidator`が呼ばれているのとテストで
```
statusCode, rec := doRequest(t, api, http.MethodGet, path, nil, &resBody)

t.Logf("Response: %v", rec.Body.String())
```
としたときに`Response: {"message":"Bad Request: validate error: limit: must be no less than 1."}`が表示されるので通っているものと認識していました。

2023-05-10 05:42 UTC, 20jun01 commented
あと、0が通過してしまいます:thonk_sweat:

2023-05-10 05:44 UTC, ras0q commented
めちゃくちゃ嘘ついてましたmockいらないです🙇🙇

2023-05-10 06:26 UTC, 20jun01 commented
もしかしてなのですが、ozzo-validationのvd.Minって0に効かなかったりします？ルールMin(1)のときに直接0を代入したのをValidationしても通ります。
`vd.NilOrNotEmpty`を組み合わせると0も弾けそうなのでそれで解決しようと思ってます。

2023-05-14 00:31 UTC, ras0q commented on integration_tests/handler/user_test.go
> +			testutils.HTTPError("Bad Request: validate error: limit: cannot be blank."),
ここ入れてるのにblankになるのか

2023-05-14 00:36 UTC, ras0q approved these changes
レビュー遅れました:bow:
よさそうです:kansya:

2023-05-14 00:36 UTC, ras0q commented on integration_tests/handler/user_test.go
> +			testutils.HTTPError("Bad Request: validate error: limit: cannot be blank."),
empty扱いだからそらそうか

2023-05-14 07:36 UTC, 20jun01 commented
:kansya:
マージします:blob_grin:

2023-05-14 07:37 UTC, merged