CASCADE をつけてDELETE /contest/:id の500エラーを修正
traPtitech/traPortfolio pull request #510
Opened 2023-04-21 11:50 UTC by ras0q

close #460

- :recycle: add constraints on update / delete
- :sparkles: add test to DeleteContest

2023-04-25 13:08 UTC, ras0q commented
DeleteContestTeamのテストを書く

2023-04-25 13:10 UTC, 0214sh7 requested changes

2023-04-25 13:10 UTC, 0214sh7 commented on integration_tests/handler/contest_test.go
> +}
DeleteContestTeamのテストも欲しい

2023-05-23 12:57 UTC, ras0q commented
@0214sh7 修正しました

2023-05-30 14:46 UTC, 0214sh7 approved these changes

2023-06-08 10:08 UTC, merged