random関数を追加
traPtitech/traPortfolio pull request #546
Opened 2023-07-27 05:34 UTC by H1rono

#395 (これでcloseするか要検討)
optionalにも足した

2023-07-27 12:03 UTC, ras0q commented on util/random/random.go
> +func UpdateContestArgs() repository.UpdateContestArgs {
他のと命名合わせるならNewすらいらない気もする

2023-07-27 22:36 UTC, ras0q requested changes

2023-07-27 22:36 UTC, ras0q commented on integration_tests/repository/contest_test.go
> +	args := *random.NewUpdateContestArgs()
ここあとで`&args`の形で使ってるので`*`なしで作って後で`args`を引数に渡せばいいと思います

2023-07-27 22:36 UTC, ras0q commented on integration_tests/repository/project_test.go
> +	arg1 := *random.NewUpdateProjectArgs()
同様

2023-07-29 04:37 UTC, ras0q commented
今更気づいたんだけどrandom.NewUpdateXXXArgsを追加したことでまたランダムでcoverageが変わる関数ができてしまったので解決にはなってないのかも、、、
やっぱりランダムなケースに加えて少なくとも1つ以上はvalid==trueになるケース(わかりにくいから全部trueの方がいいかも)を作るのがいいと思います
作ってくれた関数はそのまま使ってもいいので、全部valid==falseだったら一番上をvalid==trueにする処理を抜いて、全部trueのケースを追加してもらうのがよさそう

![image](https://github.com/traPtitech/traPortfolio/assets/66677201/e9d7f77e-99ba-4241-a7ee-b16aee43d30e)

2023-07-29 04:53 UTC, H1rono commented
:ok:

2023-07-29 05:25 UTC, H1rono commented
rebaseしました
今からテストケース追加します

2023-07-29 08:02 UTC, H1rono commented
`Of.Valid`いらなくなってる

2023-07-29 09:27 UTC, ras0q reviewed
いくつか:pray:

2023-07-29 09:27 UTC, ras0q commented on integration_tests/repository/contest_test.go
> +	tests := []struct {
table driven testともちょっと雰囲気違いそうなので`steps`の方が近いかも？
ちなみに意図的に付けてないのかもだけど`t.Parallel()`とか`go test -shuffle`とかつけると失敗するかもです

2023-07-29 09:27 UTC, ras0q commented on integration_tests/repository/project_test.go
> +			name: "no fields",
partial?

2023-07-29 09:27 UTC, ras0q commented on integration_tests/repository/user_test.go
> +		i := i + 1
もともとあったように同じindexのユーザーをアップデートすれば十分だと思います
mockそんなに多く用意してないし

2023-07-29 13:21 UTC, H1rono commented on integration_tests/repository/contest_test.go
> +	tests := []struct {
table drivenなつもりで書いたんですが、どこが雰囲気違うんでしょうか？
あと`t.Parallel()`を`t.Run`のコールバックに入れて`go test -shuffle on ./...`で実行しても通りました
全部雰囲気で進めてるのでなんもわかってないです

2023-07-29 13:23 UTC, H1rono commented on integration_tests/repository/project_test.go
> +			name: "no fields",
yes, partial

2023-07-29 13:35 UTC, H1rono commented on integration_tests/repository/user_test.go
> +		i := i + 1
`i := 1`でテストしたら落ちます
log ↓

```
2023/07/29 22:32:10 successfully loaded config from /Users/kh/Documents/trap/traPortfolio/integration_tests/testdata/config.yaml
2023/07/29 22:32:10 0
2023/07/29 22:32:10 <nil>
-test.shuffle 1690637530886112000
--- FAIL: TestUserRepository_UpdateUser (0.63s)
    --- FAIL: TestUserRepository_UpdateUser/partial_fields (0.00s)
        user_test.go:320: 
                Error Trace:    /Users/kh/Documents/trap/traPortfolio/integration_tests/repository/user_test.go:320
                Error:          Not equal: 
                                expected: &domain.UserDetail{User:domain.User{ID:[16]uint8{0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x42, 0x22, 0x82, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22}, Name:"user2", realName:"ユーザー2 ユーザー2", Check:true}, State:0x0, Bio:"I am user2", Accounts:[]*domain.Account{}}
                                actual  : &domain.UserDetail{User:domain.User{ID:[16]uint8{0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x42, 0x22, 0x82, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x22}, Name:"user2", realName:"ユーザー2 ユーザー2", Check:false}, State:0x0, Bio:"I09FN8OP8NmKHE", Accounts:[]*domain.Account{}}
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -7,6 +7,6 @@
                                   realName: (string) (len=27) "ユーザー2 ユーザー2",
                                -  Check: (bool) true
                                +  Check: (bool) false
                                  },
                                  State: (domain.TraQState) 0,
                                - Bio: (string) (len=10) "I am user2",
                                + Bio: (string) (len=14) "I09FN8OP8NmKHE",
                                  Accounts: ([]*domain.Account) {
                Test:           TestUserRepository_UpdateUser/partial_fields
FAIL
FAIL    github.com/traPtitech/traPortfolio/integration_tests/repository 2.654s
```

ので、同じユーザーに対して操作したらダメっぽいです

2023-07-30 02:19 UTC, ras0q commented on integration_tests/repository/contest_test.go
> +	tests := []struct {
各テストケースが独立じゃないのが気になるって言おうとしたんですがちゃんと見たら普通に独立でした
このままでOKです:bow:
最後のassertのところ普通に
```go
assert.Equal(t, contest1, gotContest1)
assert.Equal(t, contest2, gotContest2)
```
だけだと通らないんだっけ

2023-07-30 02:25 UTC, ras0q commented on integration_tests/repository/user_test.go
> +		i := i + 1
```go
user := mockdata.MockUsers[i]
portalUser := mockdata.MockPortalUsers[i]
traqUser := mockdata.MockTraQUsers[i]
```
をforの外に出したら多分解決します
これこそテストケースどうしが独立ではなくなるので微妙かもですが

ただ今のままやっても`i = (i+1)%len(tests)`にしてもケース増やしたらいずれ破綻するのでどうしようかな、、、という感じです
for内でユーザー作成からやるならtraQとPortalにも追加しないといけなくて記述がめんどくさそう

2023-07-30 02:25 UTC, ras0q commented on integration_tests/repository/user_test.go
> +		i := i + 1
解決はするけどt.Parallel()したら解決しないのかも

2023-07-30 04:26 UTC, H1rono commented on integration_tests/repository/contest_test.go
> +	tests := []struct {
`contest2`どこ...
変更の概略は↓です

- 返り値が捨てられている`mustMakeXXX`を削除
- s/team1/team/g, s/contest1/contest/g
- テストケースを複数作る

2023-07-30 04:33 UTC, H1rono commented on integration_tests/repository/user_test.go
> +		i := i + 1
```go
	tests := ...
	i := 1
	user := mockdata.MockUsers[i]
	portalUser := mockdata.MockPortalUsers[i]
	traqUser := mockdata.MockTraQUsers[i]
	for _, tt := range tests {
		// FIXME: i=0の時はAccountが存在するため失敗する
		//i := i + 1
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			...
```

これで`go test -shuffle on ./...`したら時々落ちるようになりました

2023-07-30 04:36 UTC, H1rono commented on integration_tests/repository/user_test.go
> +		i := i + 1
> ただ今のままやっても`i = (i+1)%len(tests)`にしてもケース増やしたらいずれ破綻するのでどうしようかな、、、という感じです

#550 とかでやります、少なくともこのPRで解決することではない

2023-07-30 05:31 UTC, ras0q approved these changes
良さそうです:+1:

2023-07-30 06:38 UTC, merged