/events APIのペイロードにeventLevelを追加
traPtitech/traPortfolio pull request #624
Opened 2024-01-11 12:51 UTC by H1rono

close #621

2024-01-13 22:39 UTC, ras0q requested changes
レビューしました

2024-01-13 22:39 UTC, ras0q commented on infrastructure/repository/event_impl.go
> +	relById := lo.Associate(rels, func(r *model.EventLevelRelation) (uuid.UUID, domain.EventLevel) {
Google Style Guidesによれば`relByID`のが良さそう

https://google.github.io/styleguide/go/decisions#initialisms

2024-01-13 22:39 UTC, ras0q commented on infrastructure/repository/event_impl.go
> +		Find(&rels).
levelの指定を無くした分取得件数が増えるのは注意する必要がありそう

この規模だとそこまで影響はなさそうな気もするけど
やや別件だけどデフォルトanonymousじゃなくてprivateにした方が良さそう (そうなるとprivate率が高くなってここの取得件数も結構変わる可能性がある)

2024-01-13 22:39 UTC, ras0q commented on infrastructure/repository/event_impl.go
> +func (r *EventRepository) completeEventLevels(ctx context.Context, events []*external.EventResponse) ([]*domain.Event, error) {
ここの変更で`completeEventLevels`が行っていることは`eventLevel`のcompleteだけじゃなくてexternal→domainのconvertとかも入ってそうだからこの命名は個人的にはびみょい

`completeEventLevels`と`filterAccessibleEvents`に分けた方が汎用性は上がるけど、どうせセットで使うのでここでの共通化は置いておいてむしろcomplete,filter,convert全部合わせて`getAccessibleEventsIn`とかの方が(externalにない`eventLevel`をどう取得するかも考えた上で)直感的な気がする(あんまり自信ない)

2024-01-13 22:39 UTC, ras0q commented on infrastructure/repository/event_impl_test.go
> +					WillReturnRows(sqlmock.NewRows([]string{"id"}))
これ追加したらここの下にあるIDとlevel同時に指定してるモッククエリ呼ばれなさそう？(下を消して欲しい)

2024-01-13 22:39 UTC, ras0q commented on infrastructure/repository/event_impl.go
> +	result = filterAccessibleEvents(result)
元の命名が悪いけどknoQから取ってくるイベントは`knoqEvents`で`result`の方を`events`にするのが良さそう

`result`の再代入あんまりやりたくない

2024-01-13 22:39 UTC, ras0q commented on domain/event.go
> +	EventLevel EventLevel
正直このPRのdiffが余計にでかくなって見づらい🤫

2024-01-13 22:39 UTC, ras0q commented on infrastructure/repository/event_impl_test.go
> +					WillReturnRows(sqlmock.NewRows([]string{"id"}))
ここも？

2024-01-14 07:56 UTC, H1rono commented on domain/event.go
> +	EventLevel EventLevel
swaggerの方も`level`にしますか？

https://github.com/traPtitech/traPortfolio/blob/fd4fd07036a4e60f72b282a6d1db80fb5e890022/docs/swagger/traPortfolio.v1.yaml#L971-L972

2024-01-14 07:57 UTC, H1rono commented on infrastructure/repository/event_impl.go
> +		Find(&rels).
> levelの指定を無くした分取得件数が増えるのは注意する必要がありそう

とりあえずコメントに残しときます

2024-01-14 07:57 UTC, ras0q commented on domain/event.go
> +	EventLevel EventLevel
しちゃっていいと思う

2024-01-14 08:14 UTC, ras0q commented on infrastructure/repository/event_impl.go
> +		Find(&rels).
issue立てるのサボってた感謝

2024-01-14 08:20 UTC, H1rono commented on infrastructure/repository/event_impl.go
> +func (r *EventRepository) completeEventLevels(ctx context.Context, events []*external.EventResponse) ([]*domain.Event, error) {
将来Adminの実装をするときにここが分かれていないと困りそうだと思ったので分けてる

`completeEventLevels`の名前が悪いのはわかる、`completeEvents`とかにしようかな

2024-01-14 08:20 UTC, H1rono commented on infrastructure/repository/event_impl_test.go
> +					WillReturnRows(sqlmock.NewRows([]string{"id"}))
確かに :crab:

2024-01-14 13:39 UTC, ras0q commented on interfaces/handler/event_test.go
> +						Level:     domain.EventLevel(random.Uint8n(uint8(domain.EventLevelLimit))),
diff増えちゃうけど`random.Iotan(domain.EventLevelLimit)`で書けた気がする

2024-01-14 13:39 UTC, ras0q commented on infrastructure/repository/event_impl.go
> +func (r *EventRepository) completeEventLevels(ctx context.Context, events []*external.EventResponse) ([]*domain.Event, error) {
completeの中にconvertが含まれてるのがどうしても気になっちゃう
completeをfillくらいのイメージだと思ってる

↑↑で全部合成って言っちゃったけど
```go
func getEventLevelMap(eventIDs []uuid.UUID) map[uuid.UUID]domain.EventLevel {}

func convertEvents(knoqEvents []*external.EventResponse, map[uuid.UUID]domain.EventLevel) []*domain.Event {}
```
の2つに分かれてる方がうれしいかも？

2024-01-15 22:57 UTC, ras0q approved these changes
よさそう！

2024-01-15 23:03 UTC, merged