:recycle: Move injector
traPtitech/traPortfolio pull request #652
Opened 2024-04-03 08:03 UTC by H1rono

close #608

2024-04-03 08:55 UTC, ras0q commented
main.goごと移動させていいと思ったけどpackageがmainになっちゃうのか

2024-04-07 05:14 UTC, H1rono commented
rebased.

2024-04-27 04:52 UTC, ras0q commented
> はい あと、go.modと同じ場所にmainがないといけないっぽい？

手元で試したけど多分このはずはないので本番と結合テストでinjectorを分けたらmain.goも移行できそう

2024-04-29 05:57 UTC, H1rono commented
- [ ] 本番のinjectorとtestのinjectorは分ける

2024-06-07 03:52 UTC, ras0q requested changes

2024-06-07 03:52 UTC, ras0q commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
c.IsProductionはassertするだけにして条件分けせずにモックを返すのが良さそう

2024-06-07 03:52 UTC, ras0q commented on integration_tests/handler/0_utils_test.go
> +func injectAPIServer(c *config.Config, db *gorm.DB) (handler.API, error) {
t.Helperにしてほしいです

2024-06-07 04:08 UTC, H1rono commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
これ僕がわかってないんだけどintegration testでモックを使うのはそういうもんなんですか

2024-06-07 04:11 UTC, H1rono commented on integration_tests/handler/0_utils_test.go
> +func injectAPIServer(c *config.Config, db *gorm.DB) (handler.API, error) {
a2b2c56

2024-06-07 04:17 UTC, H1rono commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
とりあえず 4a1dd63

2024-06-07 04:29 UTC, ras0q approved these changes
よさそうです:+1:
もしかして`injectToAPIServer`なんかなとか思ったり

2024-06-07 04:30 UTC, ras0q commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
今のテストはモック前提で書かれている箇所が多いので、、

2024-06-07 04:32 UTC, H1rono commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
ふむ
FIXME案件？

2024-06-07 04:36 UTC, H1rono commented
[injectとは・意味・使い方・読み方・例文 - 英ナビ!辞書 英和辞典](https://www.ei-navi.jp/dictionary/content/inject/)

`inject A into B`: AをBに注入する

なので`injectAPIIntoServer`とか？`injectAPIToServer`でも

2024-06-07 04:36 UTC, ras0q commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
直すならmockdataから直すことになりそうだからしばらく放置でもまあ
モチベがあれば任せます

2024-06-07 04:37 UTC, H1rono commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
コメントだけ入れとく

2024-06-07 04:42 UTC, H1rono commented
あーAPIが二重の意味持ってるのか
`injectToAPIServer`だな

2024-06-07 04:43 UTC, H1rono commented on integration_tests/handler/0_utils_test.go
> +	if c.IsProduction {
78f2a78

2024-06-07 04:49 UTC, H1rono commented
大した変更してないけど

2024-06-07 05:49 UTC, ras0q approved these changes
書いたけどoptionalなのでどっちでも

2024-06-07 05:49 UTC, ras0q commented on integration_tests/handler/0_utils_test.go
> +	// モック前提のテストがあるためassert; FIXME
```suggestion
	// FIXME: モック前提のテストがあるためassert
```
にしてくれると僕の環境でFIXMEがハイライトしてくれるのでそうしてくれると助かる
https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

2024-06-07 05:49 UTC, ras0q commented on injector.go
> +func injectIntoAPIServer(c *config.Config, db *gorm.DB) (handler.API, error) {
Inject dependencies into `handler.API`なので`injectIntoAPIServer`でいいかと思いつつも注入先の`handler.API`を引数に取りそうだよなとも思ってきた、まあいいか

2024-06-07 05:54 UTC, H1rono commented on injector.go
> +func injectIntoAPIServer(c *config.Config, db *gorm.DB) (handler.API, error) {
いいでしょ

2024-06-07 06:21 UTC, merged