wip: Contest, Projectのメンバー追加(Add)/削除(Delete)APIを編集(Edit)に統合した
traPtitech/traPortfolio pull request #675
Opened 2024-05-20 14:58 UTC by Tennessine699

#167 
#540

削除と実装のみが終わったので確認のため一旦置いとかせてください:pray:
テストの実装に問題があり詰まっていますが解決したらRevewRequestを送ります

2024-05-20 22:29 UTC, Tennessine699 commented on interfaces/handler/project.go
>  	if err := c.Bind(&req); err != nil {
contestでも同様なんですが、従来の「メンバーを全員削除する」をEditMembersでやろうとするとRequestのMembersを空っぽする必要があるのでここで `members: cannot be blank` って言われて落ちます。
これってどう回避すればいいんですか？

2024-05-20 22:40 UTC, ras0q commented on interfaces/handler/project.go
>  	if err := c.Bind(&req); err != nil {
`EditProjectMembersRequest.Validate`の中身を空配列を許すように書き換えると良いです(仕様が食い違わないようにopenapiも変更してください)

2024-05-27 23:20 UTC, ras0q requested changes

2024-05-27 23:20 UTC, ras0q commented on docs/swagger/traPortfolio.v1.yaml
> -        - members
membersのrequiredは残したままでいいと思うんですが、これ消した理由とかあります？
外すとmembersが指定されているかのチェックを自分で挟む処理が必要になりそうです

2024-05-27 23:20 UTC, ras0q commented on infrastructure/repository/contest_impl.go
> +	belongings := make(map[uuid.UUID]struct{}, len(*members))
membersがnilのときpanicする(のでrequiredでいいのではないかという話です)

2024-05-27 23:32 UTC, ras0q reviewed
追加でいくつか見ました

2024-05-27 23:32 UTC, ras0q commented on infrastructure/repository/project_impl.go
> +func (r *ProjectRepository) EditProjectMembers(ctx context.Context, projectID uuid.UUID, updatedProjectMembers []*repository.CreateProjectMemberArgs) error {
CreateProjectMemberArgsはEdit~が良さそう
updatedProjectMembersという変数名ももっといいのありそう(普通に変更前のでいい気がします)

2024-05-27 23:32 UTC, ras0q commented on infrastructure/repository/project_impl.go
> +	memberOnDatabase := make([]*model.ProjectMember, 0, len(updatedProjectMembers))
前の変数名が分かりにくすぎるので助かります！
memberOnDatabaseはあまりこのレポジトリで使われない命名な気がするのでこっちをcurrent\~にしてmapは current\~mapとするとよさそう
あと226行目はDB取得してmapを作る時に定義すると処理が読みやすくなりそうです

2024-05-27 23:32 UTC, ras0q commented on infrastructure/repository/project_impl.go
> +		}
賢い

2024-06-17 23:44 UTC, ras0q requested changes
おくれてすみません:pray:
いくつか書きました

2024-06-17 23:44 UTC, ras0q commented on infrastructure/repository/project_impl.go
> +	if err != nil && err != repository.ErrNotFound {
```suggestion
	if err != nil && !errors.Is(err, repository.ErrNotFound) {
```

2024-06-17 23:44 UTC, ras0q commented on infrastructure/repository/project_impl.go
> +		}
ここらへんはこれ使ってUpsertするのがいいと思います
https://gorm.io/ja_JP/docs/create.html#upsert

2024-06-17 23:44 UTC, ras0q commented on infrastructure/repository/contest_impl.go
>  func (r *ContestRepository) EditContestTeamMembers(ctx context.Context, teamID uuid.UUID, members []uuid.UUID) error {
EditContestTeamMembersが差分を見てアップデートする実装になってるのでEditProjectMembersに合わせるのがよさそうです

2024-06-23 07:33 UTC, ras0q commented on infrastructure/repository/project_impl.go
> +		}
コメントする場所間違えたな
changesというmapに入れなくても挿入予定のモデル(`v`)の値を更新して↓みたいに書くとupsert(db内に存在しない場合はinsert、存在する場合はupdate)ができそうです
```go
db.WithContext(ctx).Clauses(clause.OnConflict{
  Columns:   []clause.Column{{Name: "id"}},
  DoUpdates: clause.Assignments(map[string]interface{}{"role": "user"}), // ここをupsertするcolumnのmapに変える
}).Create(&users)
```

2024-06-28 13:53 UTC, ras0q commented on infrastructure/repository/project_impl.go
>  		return nil
この後に`currentProjectMembers`には存在するが`projectMembers`には存在しないメンバーを削除する必要がありそう

2024-06-28 13:57 UTC, ras0q commented on interfaces/handler/contest_test.go
> +			fmt.Printf("try: %s\n", tt.name)
消し忘れ

2024-06-28 13:58 UTC, ras0q commented on infrastructure/repository/contest_impl.go
>  func (r *ContestRepository) EditContestTeamMembers(ctx context.Context, teamID uuid.UUID, members []uuid.UUID) error {
嘘です合ってた

2024-06-28 13:59 UTC, ras0q commented on infrastructure/repository/contest_impl.go
>  func (r *ContestRepository) EditContestTeamMembers(ctx context.Context, teamID uuid.UUID, members []uuid.UUID) error {
membersToBeAddedの部分のチェックをupsertにするとprojectに合わせられそう

2024-06-28 15:09 UTC, ras0q approved these changes

2024-06-28 15:09 UTC, merged