ユーザーアカウントAPIのprPermittedに当たる要素を全て消した
traPtitech/traPortfolio pull request #739
Opened 2024-12-14 13:24 UTC by Tennessine699

resolves #678 

"prPermitted"とdatabaseのaccount.checkを消しました

2024-12-26 09:52 UTC, ras0q approved these changes
差分だけ見ました
消し忘れてたらコンパイルエラー出るはずなので良さそうです
コメントのとこだけ命名直したらマージしちゃってください

2024-12-26 09:52 UTC, ras0q commented on internal/infrastructure/migration/v3.go
> +type v3Account struct {
v3以降のaccountsテーブルにはcheckカラムがないので若干違和感あります
v3PreAccountとかv3BeforeAccountとかにしとくとわかりやすそう

2024-12-26 09:53 UTC, ras0q requested changes
あ、DBスキーマの更新してなさそう
Readme見てそれだけやってほしいです

2025-01-12 12:50 UTC, H1rono approved these changes
:+1:

2025-01-12 12:51 UTC, merged