fix swagger改正
traPtitech/traPortfolio pull request #78
Opened 2021-05-08 03:07 UTC by Ras96

swagger少し書き換えました
命名やや適当になってますが変えた方がよかったら言ってください:pray:
https://q.trap.jp/messages/f14fa3d9-c312-4410-8619-e62621e8be54

2021-05-09 09:21 UTC, Hosshii reviewed
コメントしました🙏

2021-05-09 09:21 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
> +          type: object
僕が忘れてたら申し訳ないんですが、ここを変える意図ってなんでしょうか

2021-05-09 09:21 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
> +        user_id: uuid
ここは
```
user_id: 
          type: string
          format: uuid
```
にしてください🙏

2021-05-09 09:21 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
> +          $ref: '#/components/schemas/ProjectDetail'
`ProjectDuration`ですかね？

2021-05-09 09:21 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
> +    AddProjectMember:
定義したけど使われていない気がします

2021-05-09 09:21 UTC, Hosshii commented
ちなみに僕はswaggerのファイル編集はStoplight Studioっていうアプリを使ってやってます

2021-05-09 14:30 UTC, Ras96 commented on docs/swagger/traPortfolio.v1.yaml
> +          type: object
多分ここら辺のはずです。配列の方がよかったら戻します
https://q.trap.jp/messages/64a8f51f-99df-453a-a7a7-52c9e95bc3fe

2021-05-09 14:40 UTC, Ras96 commented on docs/swagger/traPortfolio.v1.yaml
> +    AddProjectMember:
リクエストボディがMemberIDsのままでした:blob_sad:

2021-05-10 07:04 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
> +          type: object
:haakusimasita:
今のままでいいと思います

2021-05-10 07:10 UTC, Hosshii reviewed
コメントしました🙏

2021-05-10 07:10 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
> +        members:
ここあったらダメっぽいですね。
ただのarrayにするか
```
{
"members": []
}
```
みたいにしたいならobjectのなかでarrayを定義する必要がありそうです

2021-05-10 07:33 UTC, sapphi-red commented on docs/swagger/traPortfolio.v1.yaml
>              $ref: '#/components/schemas/ProjectDuration'
```suggestion
          $ref: '#/components/schemas/ProjectDuration'
```
オブジェクトにしたいならこうですね

https://swagger.io/docs/specification/data-models/data-types/#object
https://swagger.io/docs/specification/using-ref/

2021-05-10 07:53 UTC, Hosshii commented on docs/swagger/traPortfolio.v1.yaml
>              $ref: '#/components/schemas/ProjectDuration'
なるほど:kansya:

2021-05-13 15:31 UTC, Ras96 commented
多分直しました(いうの忘れてました)

2021-05-14 02:26 UTC, sapphi-red commented on docs/swagger/traPortfolio.v1.yaml
> +            $ref: '#/components/schemas/MemberIDWithProjectDuration'
ここ`required`指定してないのは意図してますか…？

2021-05-16 05:28 UTC, Ras96 commented on docs/swagger/traPortfolio.v1.yaml
> +            $ref: '#/components/schemas/MemberIDWithProjectDuration'
してませんでした、、直しておきます

2021-05-16 06:48 UTC, sapphi-red commented on docs/swagger/traPortfolio.v1.yaml
> +            - members
これインデントずれてる気がします

2021-05-16 14:51 UTC, sapphi-red approved these changes
:yosa: :desu:

2021-05-16 14:52 UTC, sapphi-red requested changes
あ、嘘でした :bow:

2021-05-16 14:52 UTC, sapphi-red commented on docs/swagger/traPortfolio.v1.yaml
> +        user_id:
camelcase(`userId`)にしてほしいです :pray:

2021-05-16 16:30 UTC, sapphi-red approved these changes
:yosa: :desu:

2021-06-04 04:33 UTC, merged